version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: plagiarism-detector-db
    restart: always
    environment:
      MYSQL_DATABASE: plagiarism_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"